Class {
	#name : #Diya2DNodeStyle,
	#superclass : #DiyaNodeStyle,
	#instVars : [
		'bgcolor',
		'color',
		'border',
		'fontSize',
		'fontFamilly',
		'borderColor',
		'width',
		'height'
	],
	#category : #'Diya-Graphics'
}

{ #category : #accessing }
Diya2DNodeStyle >> bgcolor [
	^ bgcolor
]

{ #category : #accessing }
Diya2DNodeStyle >> bgcolor: anObject [
	bgcolor := anObject
]

{ #category : #accessing }
Diya2DNodeStyle >> border [
	^ border
]

{ #category : #accessing }
Diya2DNodeStyle >> border: anObject [
	border := anObject
]

{ #category : #accessing }
Diya2DNodeStyle >> borderColor [
	^ borderColor
]

{ #category : #accessing }
Diya2DNodeStyle >> borderColor: anObject [
	borderColor := anObject
]

{ #category : #accessing }
Diya2DNodeStyle >> color [
	^ color
]

{ #category : #accessing }
Diya2DNodeStyle >> color: anObject [
	color := anObject
]

{ #category : #accessing }
Diya2DNodeStyle >> fontFamilly [
	^ fontFamilly
]

{ #category : #accessing }
Diya2DNodeStyle >> fontFamilly: anObject [
	fontFamilly := anObject
]

{ #category : #accessing }
Diya2DNodeStyle >> fontSize [
	^ fontSize
]

{ #category : #accessing }
Diya2DNodeStyle >> fontSize: anObject [
	fontSize := anObject
]

{ #category : #accessing }
Diya2DNodeStyle >> height [
	^ height
]

{ #category : #accessing }
Diya2DNodeStyle >> height: anObject [
	height := anObject
]

{ #category : #accessing }
Diya2DNodeStyle >> width [
	^ width
]

{ #category : #accessing }
Diya2DNodeStyle >> width: anObject [
	width := anObject
]
